import { Product, Promotion, Review, RestaurantLocation, CmsSection, MediaAsset, User } from '../types';

export const SEED_USERS: User[] = [
  {
    id: 'user-admin-1',
    name: 'Marcus Vance',
    email: 'admin@burgercraft.com',
    role: 'super_admin',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    phoneNumber: '+1 (555) 234-8901',
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'user-manager-1',
    name: 'Elena Rostova',
    email: 'manager@burgercraft.com',
    role: 'order_manager',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&q=80',
    phoneNumber: '+1 (555) 456-7890',
    createdAt: '2024-02-01T09:30:00Z',
  },
  {
    id: 'user-customer-1',
    name: 'Jordan Miller',
    email: 'jordan.miller@example.com',
    role: 'customer',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    phoneNumber: '+1 (555) 890-1234',
    createdAt: '2024-03-10T14:15:00Z',
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'The Double Smash King',
    slug: 'the-double-smash-king',
    category: 'burgers',
    price: 1450, // $14.50
    compareAtPrice: 1650,
    description: 'Two 100% dry-aged Angus beef patties smashed crispy, double American sharp cheddar, caramelized onions, house pickles, and signature craft smash sauce on toasted brioche.',
    fullDescription: 'Our signature masterpiece. We use a proprietary 80/20 blend of dry-aged brisket, short rib, and chuck. Pressed hard onto our 450-degree seasoned flat-top grill for that coveted lace crust, topped with double melted Wisconsin American cheddar, slow-simmered onion jam, and our tart garlic-dill pickle chips.',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=85',
    galleryImages: [
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1000&q=85',
    ],
    ingredients: ['Dry-Aged Angus Beef', 'Wisconsin Cheddar', 'Caramelized Onions', 'House Pickles', 'Smash Sauce', 'Artisan Brioche'],
    allergens: ['Dairy', 'Gluten', 'Eggs'],
    dietary: ['chef-choice'],
    calories: 880,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: true,
    salesCount: 1420,
    rating: 4.9,
    reviewCount: 382,
    modifierGroups: [
      {
        id: 'patty-size',
        name: 'Patty Upgrade',
        minSelect: 0,
        maxSelect: 1,
        required: false,
        options: [
          { id: 'opt-triple', name: 'Make it a Triple Smash (+1 Patty & Cheese)', price: 350 },
          { id: 'opt-quad', name: 'The Quadzilla (+2 Patties & Cheese)', price: 650 },
        ],
      },
      {
        id: 'bun-choice',
        name: 'Bun Style',
        minSelect: 1,
        maxSelect: 1,
        required: true,
        options: [
          { id: 'opt-brioche', name: 'Classic Butter Toasted Brioche', price: 0, isDefault: true },
          { id: 'opt-potato', name: 'Martin’s Potato Bun', price: 0 },
          { id: 'opt-lettuce', name: 'Gluten-Conscious Lettuce Wrap', price: 0 },
        ],
      },
      {
        id: 'add-ons',
        name: 'Add Extra Goodies',
        minSelect: 0,
        maxSelect: 4,
        required: false,
        options: [
          { id: 'opt-bacon', name: 'Thick Applewood Smoked Bacon', price: 250 },
          { id: 'opt-egg', name: 'Sunny-Side Fried Egg', price: 175 },
          { id: 'opt-jalapeno', name: 'Fire-Roasted Jalapeños', price: 100 },
          { id: 'opt-truffle-sauce', name: 'Black Truffle Aioli Dip', price: 150 },
        ],
      },
    ],
  },
  {
    id: 'prod-2',
    name: 'Smoked Bourbon Bacon Burger',
    slug: 'smoked-bourbon-bacon-burger',
    category: 'burgers',
    price: 1575, // $15.75
    description: 'Thick Angus beef patty glazed in Kentucky bourbon reduction, crispy applewood bacon, smoked gouda, crispy frizzled onions, and smoky garlic mayo.',
    fullDescription: 'Rich, deep, and savory. We slow-smoke the bacon over hickory chips, char our Angus patty to juicy medium, and top it with aromatic smoked Dutch gouda cheese. Finished with crispy hand-battered frizzled shallots and our house-made bourbon-blackstrap molasses glaze.',
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=1000&q=85',
    galleryImages: [
      'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=85',
    ],
    ingredients: ['Angus Patty', 'Applewood Bacon', 'Smoked Gouda', 'Crispy Frizzled Onions', 'Bourbon Glaze', 'Brioche Bun'],
    allergens: ['Dairy', 'Gluten', 'Eggs'],
    dietary: ['chef-choice'],
    calories: 940,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: true,
    salesCount: 1190,
    rating: 4.8,
    reviewCount: 295,
  },
  {
    id: 'prod-3',
    name: 'Firebird Nashville Hot Chicken',
    slug: 'firebird-nashville-hot-chicken',
    category: 'chicken',
    price: 1395,
    description: 'Buttermilk-brined double crispy chicken thigh dredged in fiery cayenne oil, chilled cabbage slaw, sweet bread & butter pickles, and comeback sauce.',
    fullDescription: 'Marinated for 24 hours in farm buttermilk and Louisiana seasonings, then fried golden brown until extraordinarily crunchy. Hand-dipped in hot spiced chili lard and balanced with crisp vinegar slaw and thick pickles.',
    imageUrl: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=1000&q=85',
    galleryImages: [
      'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=1000&q=85',
    ],
    ingredients: ['Buttermilk Fried Chicken Thigh', 'Nashville Chili Oil', 'Vinegar Slaw', 'Bread & Butter Pickles', 'Comeback Sauce'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    dietary: ['spicy'],
    calories: 820,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: false,
    salesCount: 880,
    rating: 4.9,
    reviewCount: 210,
  },
  {
    id: 'prod-4',
    name: 'The Truffle Mushroom Swiss',
    slug: 'the-truffle-mushroom-swiss',
    category: 'burgers',
    price: 1625,
    description: 'Seared Angus patty topped with sautéed wild cremini and shiitake mushrooms, melted Swiss Emmental, fresh baby arugula, and black truffle crema.',
    fullDescription: 'Earthy, umami-packed sophistication. Fresh wild mushrooms sautéed in garlic thyme butter over a juicy patty, covered under melted cave-aged Swiss cheese with peppery wild arugula.',
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1000&q=85',
    galleryImages: ['https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1000&q=85'],
    ingredients: ['Angus Beef', 'Wild Shiitake & Cremini', 'Swiss Emmental', 'Baby Arugula', 'Truffle Crema'],
    allergens: ['Dairy', 'Gluten', 'Eggs'],
    dietary: ['chef-choice'],
    calories: 860,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: false,
    salesCount: 640,
    rating: 4.7,
    reviewCount: 145,
  },
  {
    id: 'prod-5',
    name: 'Hand-Cut Parmesan Truffle Fries',
    slug: 'hand-cut-parmesan-truffle-fries',
    category: 'sides',
    price: 675,
    description: 'Double-fried Idaho Russet potatoes tossed in fragrant white truffle oil, sea salt, chopped Italian parsley, and freshly grated 24-month Parmigiano Reggiano.',
    fullDescription: 'Crisp on the outside, fluffy like cloud on the inside. Double-cooked in pure peanut oil, then tossed right out of the fryer with real white truffle oil and generous micro-planed Parmigiano.',
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=1000&q=85',
    galleryImages: ['https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=1000&q=85'],
    ingredients: ['Idaho Potatoes', 'White Truffle Oil', 'Parmigiano Reggiano', 'Parsley', 'Sea Salt'],
    allergens: ['Dairy'],
    dietary: ['vegetarian', 'gluten-free'],
    calories: 420,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: true,
    salesCount: 2310,
    rating: 4.9,
    reviewCount: 512,
  },
  {
    id: 'prod-6',
    name: 'Smoky Chipotle Onion Rings',
    slug: 'smoky-chipotle-onion-rings',
    category: 'sides',
    price: 595,
    description: 'Colossal sweet Vidalia onions hand-dipped in craft beer batter, fried shattering crisp, served with charred chipotle crema.',
    fullDescription: 'Made fresh from scratch every morning. Thick cut rings of naturally sweet onions bathed in IPA batter and fried crisp.',
    imageUrl: 'https://images.unsplash.com/photo-1639024471287-032f66ab71c0?auto=format&fit=crop&w=1000&q=85',
    galleryImages: ['https://images.unsplash.com/photo-1639024471287-032f66ab71c0?auto=format&fit=crop&w=1000&q=85'],
    ingredients: ['Vidalia Onions', 'Craft Beer Batter', 'Chipotle Dip', 'Sea Salt'],
    allergens: ['Gluten', 'Eggs'],
    dietary: ['vegetarian'],
    calories: 390,
    isAvailable: true,
    isFeatured: false,
    isBestSeller: false,
    salesCount: 920,
    rating: 4.6,
    reviewCount: 160,
  },
  {
    id: 'prod-7',
    name: 'Double Smash Feast Combo',
    slug: 'double-smash-feast-combo',
    category: 'combos',
    price: 2095,
    compareAtPrice: 2450,
    description: 'Includes The Double Smash King, large Hand-Cut Truffle Fries, and any craft house drink or hand-spun shake.',
    fullDescription: 'Our most popular all-in-one meal. Save $3.55 when bundling your favorite burger, gourmet fries, and cold drink.',
    imageUrl: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=1000&q=85',
    galleryImages: ['https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=1000&q=85'],
    ingredients: ['Double Smash King', 'Truffle Fries', 'Craft Beverage'],
    allergens: ['Dairy', 'Gluten', 'Eggs'],
    dietary: ['chef-choice'],
    calories: 1450,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: true,
    salesCount: 1750,
    rating: 5.0,
    reviewCount: 420,
  },
  {
    id: 'prod-8',
    name: 'Madagascar Vanilla Bean Shake',
    slug: 'madagascar-vanilla-bean-shake',
    category: 'drinks',
    price: 650,
    description: 'Small-batch organic custard spun thick with real scraped Madagascar bourbon vanilla beans and whipped heavy cream.',
    fullDescription: 'Old-school soda fountain style. No syrups, no powders. Made with local creamery frozen custard and real vanilla bean specks.',
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=1000&q=85',
    galleryImages: ['https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=1000&q=85'],
    ingredients: ['Organic Custard', 'Madagascar Vanilla', 'Heavy Cream'],
    allergens: ['Dairy'],
    dietary: ['vegetarian', 'gluten-free'],
    calories: 540,
    isAvailable: true,
    isFeatured: false,
    isBestSeller: false,
    salesCount: 1100,
    rating: 4.8,
    reviewCount: 198,
  },
  {
    id: 'prod-9',
    name: 'House Smoked Sea Salt Caramel Tart',
    slug: 'sea-salt-caramel-tart',
    category: 'desserts',
    price: 695,
    description: 'Crisp buttery shortcrust pastry filled with dark dark chocolate ganache, gooey smoked salted caramel, and toasted almond flakes.',
    fullDescription: 'The perfect decadent finish to a hearty craft burger dinner.',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1000&q=85',
    galleryImages: ['https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1000&q=85'],
    ingredients: ['Dark Chocolate', 'Smoked Caramel', 'Almonds', 'Butter Pastry'],
    allergens: ['Dairy', 'Gluten', 'Nuts'],
    dietary: ['vegetarian'],
    calories: 460,
    isAvailable: true,
    isFeatured: false,
    isBestSeller: false,
    salesCount: 510,
    rating: 4.9,
    reviewCount: 94,
  },
];

export const SEED_PROMOTIONS: Promotion[] = [
  {
    id: 'promo-1',
    code: 'SMASH20',
    title: '20% Off Your First Online Order',
    description: 'Get 20% off your entire order when you order $25 or more through our website.',
    discountType: 'percentage',
    discountValue: 20,
    minOrderAmount: 2500, // $25.00
    maxDiscount: 1000, // $10.00 max
    startDate: '2024-01-01',
    endDate: '2026-12-31',
    usageLimit: 5000,
    timesUsed: 1342,
    isActive: true,
    bannerText: 'Use code SMASH20 for 20% off orders over $25',
  },
  {
    id: 'promo-2',
    code: 'FEAST5',
    title: '$5 Off Any Family or Combo Order',
    description: 'Take $5.00 off any order containing combos or signature burgers.',
    discountType: 'fixed',
    discountValue: 500, // $5.00
    minOrderAmount: 3000,
    startDate: '2024-01-01',
    endDate: '2026-12-31',
    usageLimit: 2000,
    timesUsed: 620,
    isActive: true,
    bannerText: 'Save $5 on orders over $30 with FEAST5',
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    customerName: 'Harrison Davis',
    rating: 5,
    comment: 'Without exaggeration, the lace crust on the Double Smash King is the crispiest and most flavorful I have experienced anywhere on the East Coast. Brioche holds up until the very last bite.',
    productName: 'The Double Smash King',
    date: '2024-03-12',
    isApproved: true,
    isFeatured: true,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
  },
  {
    id: 'rev-2',
    customerName: 'Chef Clara Nguyen',
    rating: 5,
    comment: 'As someone who has worked in high-end culinary kitchens for 12 years, their meat blend balance and the temperature precision on the flat-top grill are masterclass. The parmesan truffle fries are sensational.',
    productName: 'Hand-Cut Parmesan Truffle Fries',
    date: '2024-03-08',
    isApproved: true,
    isFeatured: true,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
  },
  {
    id: 'rev-3',
    customerName: 'Devon Scott',
    rating: 5,
    comment: 'Ordering online took less than 45 seconds, the pickup order was piping hot right as I arrived, and the bourbon bacon burger has officially ruined all other burgers for me.',
    productName: 'Smoked Bourbon Bacon Burger',
    date: '2024-02-27',
    isApproved: true,
    isFeatured: true,
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80',
  },
];

export const SEED_LOCATIONS: RestaurantLocation[] = [
  {
    id: 'loc-1',
    name: 'Downtown Flagship & Grill',
    address: '428 Lexington Avenue, Suite 100',
    city: 'New York',
    state: 'NY',
    zipCode: '10017',
    phone: '+1 (212) 555-0192',
    hours: 'Mon-Sun: 11:00 AM - 11:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    mapCoordinates: { lat: 40.7516, lng: -73.9755 },
    supportsPickup: true,
    supportsDelivery: true,
  },
  {
    id: 'loc-2',
    name: 'Brooklyn Waterfront Kitchen',
    address: '88 Water Street, DUMBO',
    city: 'Brooklyn',
    state: 'NY',
    zipCode: '11201',
    phone: '+1 (718) 555-0144',
    hours: 'Mon-Sun: 11:30 AM - 10:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    mapCoordinates: { lat: 40.7033, lng: -73.9904 },
    supportsPickup: true,
    supportsDelivery: true,
  },
  {
    id: 'loc-3',
    name: 'SoHo Craft Tavern',
    address: '154 Spring Street',
    city: 'New York',
    state: 'NY',
    zipCode: '10012',
    phone: '+1 (212) 555-0188',
    hours: 'Sun-Thu: 11:00 AM - Midnight, Fri-Sat: 11:00 AM - 2:00 AM',
    imageUrl: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80',
    mapCoordinates: { lat: 40.7252, lng: -74.0006 },
    supportsPickup: true,
    supportsDelivery: false,
  },
];

export const SEED_MEDIA_ASSETS: MediaAsset[] = [
  {
    id: 'media-1',
    fileName: 'double-smash-hero.jpg',
    url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=85',
    fileSize: 1048576,
    mimeType: 'image/jpeg',
    altText: 'The Double Smash King burger on parchment with melted cheese',
    category: 'hero',
    createdAt: '2024-01-10T10:00:00Z',
    usageCount: 3,
  },
  {
    id: 'media-2',
    fileName: 'bourbon-bacon.jpg',
    url: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=1200&q=85',
    fileSize: 980000,
    mimeType: 'image/jpeg',
    altText: 'Smoked Bourbon Bacon Burger with crispy frizzled onions',
    category: 'products',
    createdAt: '2024-01-11T11:00:00Z',
    usageCount: 2,
  },
  {
    id: 'media-3',
    fileName: 'nashville-chicken.jpg',
    url: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=1200&q=85',
    fileSize: 1120000,
    mimeType: 'image/jpeg',
    altText: 'Crispy Nashville Hot Chicken sandwich with fresh pickles and slaw',
    category: 'products',
    createdAt: '2024-01-12T12:00:00Z',
    usageCount: 1,
  },
  {
    id: 'media-4',
    fileName: 'parmesan-fries.jpg',
    url: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=1200&q=85',
    fileSize: 760000,
    mimeType: 'image/jpeg',
    altText: 'Golden hand-cut fries seasoned with truffle oil and shaved parmesan',
    category: 'products',
    createdAt: '2024-01-13T09:00:00Z',
    usageCount: 2,
  },
  {
    id: 'media-5',
    fileName: 'restaurant-interior.jpg',
    url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=85',
    fileSize: 1450000,
    mimeType: 'image/jpeg',
    altText: 'Warm rustic diner dining room with exposed brick and warm glowing lights',
    category: 'restaurant',
    createdAt: '2024-01-08T15:00:00Z',
    usageCount: 2,
  },
];

// Initial Homepage Sections for the Visual CMS
export const INITIAL_CMS_SECTIONS: CmsSection[] = [
  {
    id: 'sec-announcement',
    type: 'announcement',
    title: 'Top Announcement Banner',
    isVisible: true,
    content: {
      text: 'USE CODE SMASH20 FOR 20% OFF ALL ONLINE ORDERS OVER $25',
      ctaText: 'Claim Code',
      ctaLink: '/deals',
      backgroundColor: '#A82D24',
      textColor: '#FFFFFF',
    },
  },
  {
    id: 'sec-hero',
    type: 'hero',
    title: 'Main Hero Section',
    isVisible: true,
    content: {
      badge: 'CRAFTED FRESH DAILY',
      headline: 'REAL DRY-AGED SMASH BURGERS.',
      description: 'Hand-pressed on 450° cast iron for that legendary crispy lace crust. Made with 100% grass-fed Angus beef, house-baked brioche, and secret craft sauce.',
      primaryCtaText: 'Order Online Now',
      primaryCtaLink: '/menu',
      secondaryCtaText: 'Build Your Own Burger',
      secondaryCtaLink: '/build-your-burger',
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=85',
      imageAlt: 'The Double Smash King with melted cheese on toasted brioche',
      backgroundColor: '#171717',
      textColor: '#FAF8F3',
      statsValue: '4.9 ★',
      statsLabel: 'Over 2,400 Verified Reviews',
      bgStyle: 'dark-grill',
      bgImageUrl: '/images/hero-restaurant-bg.jpg',
      bgOverlayOpacity: 88,
      slides: [
        {
          id: 'slide-1',
          imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=85',
          imageAlt: 'The Double Smash King with melted cheese on toasted brioche',
          badge: '🔥 450° Cast Iron Sizzle',
          label: '100% Certified Angus Beef',
        },
        {
          id: 'slide-2',
          imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=1200&q=85',
          imageAlt: 'Truffle Bacon Jam Burger',
          badge: '🥓 Smoked Applewood Bacon',
          label: 'House Truffle Aioli Jam',
        },
        {
          id: 'slide-3',
          imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=85',
          imageAlt: 'Spicy Firehouse Smash Burger',
          badge: '🌶️ Nashville Hot Glaze',
          label: 'Crispy Fried Pickles & Slaw',
        },
        {
          id: 'slide-4',
          imageUrl: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&w=1200&q=85',
          imageAlt: 'Double Cheddar Deluxe',
          badge: '🧀 Wisconsin Sharp Cheddar',
          label: 'Artisan Potato Brioche Bun',
        },
      ],
    },
  },
  {
    id: 'sec-categories',
    type: 'categories',
    title: 'Featured Categories',
    isVisible: true,
    content: {
      tagline: 'CURATED SELECTIONS',
      heading: 'EXPLORE OUR CRAFT MENU',
    },
  },
  {
    id: 'sec-signature',
    type: 'signature_burgers',
    title: 'Signature Smash Burgers',
    isVisible: true,
    content: {
      tagline: 'CHEF SELECTIONS',
      heading: 'OUR SIGNATURE CREATIONS',
      description: 'Every burger is ground fresh in-house every single morning and pressed to sizzling perfection.',
    },
  },
  {
    id: 'sec-promo',
    type: 'promo_feature',
    title: 'Promotional Feature Banner',
    isVisible: true,
    content: {
      tag: 'LIMITED TIME VALUE MEAL',
      headline: 'THE DOUBLE SMASH FEAST COMBO',
      description: 'The Double Smash King, large Hand-Cut Truffle Fries, and any craft beverage. Save $3.55 compared to ordering à la carte.',
      discountBadge: 'SAVE $3.55',
      ctaText: 'Order Combo Meal ($20.95)',
      ctaLink: '/menu?item=prod-7',
      imageUrl: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=1000&q=85',
    },
  },
  {
    id: 'sec-why-us',
    type: 'why_choose_us',
    title: 'Why Choose Burger Craft',
    isVisible: true,
    content: {
      tagline: 'THE CRAFT PHILOSOPHY',
      heading: 'UNCOMPROMISING QUALITY IN EVERY DETAIL',
      items: [
        {
          id: 'why-1',
          iconName: 'Flame',
          title: 'Cast-Iron Smashed',
          description: 'High-heat sear creates maximum caramelization and an unforgettable crunchy lace edge.',
        },
        {
          id: 'why-2',
          iconName: 'Beef',
          title: 'Dry-Aged Angus Blend',
          description: 'A 28-day aged blend of short rib, chuck, and brisket. Ground fresh twice daily.',
        },
        {
          id: 'why-3',
          iconName: 'Wheat',
          title: 'Artisan Brioche',
          description: 'Baked fresh every morning with pure sweet cream butter. Golden, light, and pillowy.',
        },
        {
          id: 'why-4',
          iconName: 'Clock',
          title: 'Lightning Hot Pickup',
          description: 'Prepared strictly to order in 8 minutes or less. Never heat-lamped or pre-cooked.',
        },
      ],
    },
  },
  {
    id: 'sec-best-sellers',
    type: 'best_sellers',
    title: 'Best Sellers Section',
    isVisible: true,
    content: {
      tagline: 'CROWD FAVORITES',
      heading: 'TOP ORDERED ITEMS THIS WEEK',
    },
  },
  {
    id: 'sec-build-burger',
    type: 'build_burger',
    title: 'Build Your Burger Teaser',
    isVisible: true,
    content: {
      tagline: 'CUSTOM CREATIONS',
      heading: 'DESIGN YOUR MASTERPIECE',
      description: 'Choose your patty blend, artisan bun, aged cheeses, fire-roasted veggies, and signature dips.',
      ctaText: 'Start Customizing Now',
      ctaLink: '/build-your-burger',
      imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1000&q=85',
    },
  },
  {
    id: 'sec-story',
    type: 'brand_story',
    title: 'Brand Story Section',
    isVisible: true,
    content: {
      eyebrow: 'SINCE 2018',
      title: 'ROOTED IN PASSION FOR AUTHENTIC AMERICAN DINER HERITAGE',
      paragraph1: 'We started Burger Craft with one simple obsession: burgers were meant to be made with real, honest craftsmanship rather than industrial speed.',
      paragraph2: 'We partnered directly with sustainable family pastures in upstate New York, commissioned custom cast iron grills, and spent eight months perfecting our bun recipe. The result is pure, unadulterated flavor.',
      stat1Number: '100%',
      stat1Label: 'Grass-Fed Angus Beef',
      stat2Number: '28-Day',
      stat2Label: 'Dry-Aged Precision',
      imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=85',
    },
  },
  {
    id: 'sec-reviews',
    type: 'reviews',
    title: 'Customer Reviews Section',
    isVisible: true,
    content: {
      tagline: 'CUSTOMER VOICES',
      heading: 'WHAT OUR GUESTS ARE SAYING',
    },
  },
  {
    id: 'sec-locations',
    type: 'locations',
    title: 'Restaurant Locations Section',
    isVisible: true,
    content: {
      tagline: 'VISIT US',
      heading: 'THREE CONVENIENT LOCATIONS',
      description: 'Dine-in with retro vinyl hospitality, or order ahead for rapid curbside pickup.',
    },
  },
  {
    id: 'sec-newsletter',
    type: 'newsletter',
    title: 'Newsletter Subscription Section',
    isVisible: true,
    content: {
      heading: 'JOIN THE CRAFT BURGER CLUB',
      description: 'Receive secret off-menu specials, exclusive launch invites, and $5 off your next order.',
      buttonText: 'Subscribe Now',
      disclaimer: 'We respect your inbox. Unsubscribe anytime with 1 click.',
    },
  },
  {
    id: 'sec-social',
    type: 'social_gallery',
    title: 'Social Gallery Section',
    isVisible: true,
    content: {
      tagline: '@BURGERCRAFTNYC',
      heading: 'TAG US IN YOUR CRAFT CREATIONS',
      images: [
        'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
      ],
    },
  },
];
